### ISSUE TITLE
Correct bug in db/seeds

### ISSUE THREAD

**Issue by alexvirtualbr** [J-Cunha/cryptocoinsmap#30]
Hi,

I'm having a problem when I try to do a reboot in db at development time, that's all! :)

I run a "rails db: reset" and everything runs fine up a line 4167. See above:

>>
redirection forbidden: https://coinmarketcap.com/currencies/views/all/ -> http://coinmarketcap.com/coins/views/all/
/media/alexvirtualbr/Storage/Workspace/RubyOnRails/cryptocoinsmap/db/seeds.rb:4167:in `<top (required)>'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine.rb:549:in `load_seed'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:270:in `load_seed'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:184:in `block (2 levels) in <top (required)>'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/media/alexvirtualbr/Storage/Workspace/RubyOnRails/cryptocoinsmap/bin/rails:9:in `require'
/media/alexvirtualbr/Storage/Workspace/RubyOnRails/cryptocoinsmap/bin/rails:9:in `<top (required)>'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/alexvirtualbr/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/media/alexvirtualbr/Storage/Workspace/RubyOnRails/cryptocoinsmap/bin/spring:15:in `require'
/media/alexvirtualbr/Storage/Workspace/RubyOnRails/cryptocoinsmap/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
(See full trace by running task with --trace)
>>

**Comment by J-Cunha** [comment]
I wil check the bug.
